# Site settings
title: Bike Videos
description: >
  These are some awesome educational videos about the history of the bicycle.
url: "https://jekyll-t-richards.c9users.io/"
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - node_modules
  - yarn.lock
  - Makefile

# Collections
collections:
  bikes:
    output: true
    permalink: /bikes/:title/

# Assets
assets:
  sources:
    - node_modules